name: Deploy docs to IPFS through Pinata
on: [push]
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - run ipfs pin remote service add pinata https://api.pinata.cloud/psa ${{ secrets.PINATA_JWT }}
      - ipfs add docs/build/html -r -Q | ipfs pin remote add --service=pinata --name=orbitdb-docs
